# Generated by Django 4.2.9 on 2024-01-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[(1, 'Лор'), (2, 'Неврология')], max_length=2)),
            ],
        ),
    ]
